### ISSUE TITLE
FirstSpirit CaaS - Link in Introduction is dead

### ISSUE THREAD

**Issue by aruppert** [e-Spirit/fsxa-pwa#41]
Hi,

here : https://github.com/e-Spirit/fsxa-pwa/blob/master/docs/modules/ROOT/pages/Introduction.adoc#general this is dead - 404 : 
![image](https://user-images.githubusercontent.com/56864263/130350462-eb1ce256-3f27-41dc-9bc5-3e8e89c10ad0.png)
( https://docs.e-spirit.com/module/caas/CaaS_Platform_Documentation_EN.html )
Just the best

**Comment by dbarczewski** [comment]
Hi @aruppert 

Thank you very much for reporting this issue. 
We have fixed it in https://github.com/e-Spirit/fsxa-pwa/commit/e0cb2c1259a1fc4e39f8c15acad5240284960eea
