### ISSUE TITLE
Expand fsxa.config capabilities for Project Folders

### ISSUE THREAD

**Issue by webfussel** [e-Spirit/fsxa-pwa#62]
**Description**
Currently we are implementing unit tests in our fsxa-pwa powered nuxt app.
We decided to put the unit tests beside the component into the same folders so components and tests are in the same place every time.

As we also want to test mapping functions used in our `fsxa/sections` templates we would also like to write unit tests for those.

**Problem**
When starting the application after setting up the unit tests the FSXA Library also collects the unit tests and treats them as if they're also components. This leads to errors such as `Reference Error: describe is not defined` as describe is one of the functions used bei `jest` for unit testing.

That happends because as stated in the description of the configuration it will auto collect every file with the extensions `.vue`, `.tsx`, `.jsx` and `.ts` and our unit test files of course are ending with `.ts` in a TypeScript project.

**Proposals**

**Allow file extension filtering**
This proposal is directly taken from the Nuxt config, as they also allow to only collect components when files have specific extensions.
```js
export default {
  components: {
    sections: { path: '~/components/fsxa/sections', extensions: ['vue', 'tsx'] },
  },
}
```

**Allow globs**
This is a standard approach used by many tools such as `webpack`.

```js
export default {
  components: {
    sections: '**/components/fsxa/sections/**/*.(vue|tsx)',
  },
}
```

**Allow ignores with globs or extensions**

```js
export default {
  components: {
    sections: { path: '**/components/fsxa/sections/', ignore: '*.test.*' },
    layouts: { path: '**/components/fsxa/layouts/', ignore: ['ts'] },
  },
}
```

In the best case some mixture of those is implenented, but more freedom would be appreciated.

A quick fix for our project is to just not put unit tests into those directories, but that would break the whole directory structure and would be inconsistent with the rest of the project.

**Comment by webfussel** [comment]
Just found out I messed up the project to post this. I will recreate this ticket in [fsxa-pattern-library](https://github.com/e-Spirit/fsxa-pattern-library)

**Comment by henczi-espirit** [comment]
@webfussel No need to move this issue :-)
Thank you for opening up this topic.
The problem you described is reasonable. The solution for it would be a fix in our [fsxa-nuxt-module](https://github.com/e-Spirit/fsxa-nuxt-module), in which the configuration should be expanded in such way, that not only strings are allowed in the components objects' properties.

I think the cleanest way to go would be to support the same configuration possibilities that are used in the nuxt.config (https://nuxtjs.org/docs/configuration-glossary/configuration-components/). 

How urgent is this fix for your project?

**Comment by webfussel** [comment]
Hey @henczi-espirit !
First: I'm deeply sorry if I created some chaos with the new ticket in the (sadly again...) wrong ticket board. And thank you for your answer.

I agree the cleanest way would be a configuration that's already present in a library used in the project - nuxt in that case.
(They also provide a `.nuxtignore` if that's something you could also consider)

Currently the setup for our unit tests is done on a separate branch, so I don't need the fix right now - but as we want to merge soon (about 1 or 2 weeks from now) it would be nice if it's fixed by then.

**Comment by henczi-espirit** [comment]
@webfussel I created a ticket for this in our internal Jira, but I cannot promise that the feature will arrive soon enough for your project, for there are a higher prioritized tickets before it. Though I will speak with the developers, if someone could attach this feature to their ticket.

**Comment by webfussel** [comment]
Thanks a lot!
